// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZdii93DoxgPtPCz2rn31qJCstm4IHCpU',
    appId: '1:1060137572460:web:76925d522caa405636e049',
    messagingSenderId: '1060137572460',
    projectId: 'watchhub1-8fce4',
    authDomain: 'watchhub1-8fce4.firebaseapp.com',
    storageBucket: 'watchhub1-8fce4.firebasestorage.app',
    measurementId: 'G-KMD4K0WZ8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAt0BM0ZxeAemz6SPYMHXuDkItDK2_sTQ',
    appId: '1:1060137572460:android:4517d804aaaf03f436e049',
    messagingSenderId: '1060137572460',
    projectId: 'watchhub1-8fce4',
    storageBucket: 'watchhub1-8fce4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDRU7ai3LG6Nso1el_eE8pnUy4eMWWrbs',
    appId: '1:1060137572460:ios:041d4c71fc8ee50536e049',
    messagingSenderId: '1060137572460',
    projectId: 'watchhub1-8fce4',
    storageBucket: 'watchhub1-8fce4.firebasestorage.app',
    iosBundleId: 'com.example.watchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDRU7ai3LG6Nso1el_eE8pnUy4eMWWrbs',
    appId: '1:1060137572460:ios:041d4c71fc8ee50536e049',
    messagingSenderId: '1060137572460',
    projectId: 'watchhub1-8fce4',
    storageBucket: 'watchhub1-8fce4.firebasestorage.app',
    iosBundleId: 'com.example.watchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZdii93DoxgPtPCz2rn31qJCstm4IHCpU',
    appId: '1:1060137572460:web:0ec38d9377e22d0b36e049',
    messagingSenderId: '1060137572460',
    projectId: 'watchhub1-8fce4',
    authDomain: 'watchhub1-8fce4.firebaseapp.com',
    storageBucket: 'watchhub1-8fce4.firebasestorage.app',
    measurementId: 'G-V950GDGHEE',
  );
}
